-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local SglMsg_pb = require("SglMsg_pb")
module('Auth_pb')


SGLAUTHMSG = protobuf.Descriptor()
local SGLAUTHMSG_F = {}
SGLAUTHMSG_F.AUTHENTICATION_FIELD = protobuf.FieldDescriptor()
SGLAUTHMSG_F.AGENT_FIELD = protobuf.FieldDescriptor()
SGLAUTHMSG_F.PASS_FIELD = protobuf.FieldDescriptor()
SGLAUTHMSG_F.CHALLENGE_FIELD = protobuf.FieldDescriptor()

SGLAUTHMSG_F.AUTHENTICATION_FIELD.name = "authentication"
SGLAUTHMSG_F.AUTHENTICATION_FIELD.full_name = ".sgland.SglAuthMsg.authentication"
SGLAUTHMSG_F.AUTHENTICATION_FIELD.number = 100
SGLAUTHMSG_F.AUTHENTICATION_FIELD.index = 0
SGLAUTHMSG_F.AUTHENTICATION_FIELD.label = 1
SGLAUTHMSG_F.AUTHENTICATION_FIELD.has_default_value = false
SGLAUTHMSG_F.AUTHENTICATION_FIELD.default_value = ""
SGLAUTHMSG_F.AUTHENTICATION_FIELD.type = 12
SGLAUTHMSG_F.AUTHENTICATION_FIELD.cpp_type = 9

SGLAUTHMSG_F.AGENT_FIELD.name = "agent"
SGLAUTHMSG_F.AGENT_FIELD.full_name = ".sgland.SglAuthMsg.agent"
SGLAUTHMSG_F.AGENT_FIELD.number = 101
SGLAUTHMSG_F.AGENT_FIELD.index = 1
SGLAUTHMSG_F.AGENT_FIELD.label = 1
SGLAUTHMSG_F.AGENT_FIELD.has_default_value = false
SGLAUTHMSG_F.AGENT_FIELD.default_value = ""
SGLAUTHMSG_F.AGENT_FIELD.type = 9
SGLAUTHMSG_F.AGENT_FIELD.cpp_type = 9

SGLAUTHMSG_F.PASS_FIELD.name = "pass"
SGLAUTHMSG_F.PASS_FIELD.full_name = ".sgland.SglAuthMsg.pass"
SGLAUTHMSG_F.PASS_FIELD.number = 102
SGLAUTHMSG_F.PASS_FIELD.index = 2
SGLAUTHMSG_F.PASS_FIELD.label = 1
SGLAUTHMSG_F.PASS_FIELD.has_default_value = false
SGLAUTHMSG_F.PASS_FIELD.default_value = ""
SGLAUTHMSG_F.PASS_FIELD.type = 9
SGLAUTHMSG_F.PASS_FIELD.cpp_type = 9

SGLAUTHMSG_F.CHALLENGE_FIELD.name = "challenge"
SGLAUTHMSG_F.CHALLENGE_FIELD.full_name = ".sgland.SglAuthMsg.challenge"
SGLAUTHMSG_F.CHALLENGE_FIELD.number = 100
SGLAUTHMSG_F.CHALLENGE_FIELD.index = 3
SGLAUTHMSG_F.CHALLENGE_FIELD.label = 1
SGLAUTHMSG_F.CHALLENGE_FIELD.has_default_value = false
SGLAUTHMSG_F.CHALLENGE_FIELD.default_value = ""
SGLAUTHMSG_F.CHALLENGE_FIELD.type = 12
SGLAUTHMSG_F.CHALLENGE_FIELD.cpp_type = 9

SGLAUTHMSG.name = "SglAuthMsg"
SGLAUTHMSG.full_name = ".sgland.SglAuthMsg"
SGLAUTHMSG.nested_types = {}
SGLAUTHMSG.enum_types = {}
SGLAUTHMSG.fields = {}
SGLAUTHMSG.is_extendable = false
SGLAUTHMSG.extensions = {SGLAUTHMSG_F.AUTHENTICATION_FIELD, SGLAUTHMSG_F.AGENT_FIELD, SGLAUTHMSG_F.PASS_FIELD, SGLAUTHMSG_F.CHALLENGE_FIELD}

SglAuthMsg = protobuf.Message(SGLAUTHMSG)

SglMsg_pb.SglReqMsg.RegisterExtension(SGLAUTHMSG_F.AUTHENTICATION_FIELD)
SglMsg_pb.SglReqMsg.RegisterExtension(SGLAUTHMSG_F.AGENT_FIELD)
SglMsg_pb.SglReqMsg.RegisterExtension(SGLAUTHMSG_F.PASS_FIELD)
SglMsg_pb.SglRespMsg.RegisterExtension(SGLAUTHMSG_F.CHALLENGE_FIELD)
