-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local SglMsg_pb = require("SglMsg_pb")
local Data_pb = require("Data_pb")
module('Chat_pb')


CHATTYPE = protobuf.EnumDescriptor()
local CHATTYPE_E = {}
CHATTYPE_E.PB_CHAT_WORLD = protobuf.EnumValueDescriptor();
CHATTYPE_E.PB_CHAT_UNION = protobuf.EnumValueDescriptor();
CHATTYPE_E.PB_CHAT_PRIVATE = protobuf.EnumValueDescriptor();
CHAT = protobuf.Descriptor()
local CHAT_F = {}
CHAT_F.TYPE_FIELD = protobuf.FieldDescriptor()
CHAT_F.USER_INFO_FIELD = protobuf.FieldDescriptor()
CHAT_F.CONTENT_FIELD = protobuf.FieldDescriptor()
CHAT_F.TIMESTAMP_FIELD = protobuf.FieldDescriptor()
CHAT_F.IS_IMPORTANT_FIELD = protobuf.FieldDescriptor()
CHATSENDREQ = protobuf.Descriptor()
local CHATSENDREQ_F = {}
CHATSENDREQ_F.TYPE_FIELD = protobuf.FieldDescriptor()
CHATSENDREQ_F.ID_FIELD = protobuf.FieldDescriptor()
CHATSENDREQ_F.CONTENT_FIELD = protobuf.FieldDescriptor()
SGLCHATMSG = protobuf.Descriptor()
local SGLCHATMSG_F = {}
SGLCHATMSG_F.CHAT_SEND_REQ_FIELD = protobuf.FieldDescriptor()
SGLCHATMSG_F.CHAT_RECEIVE_RESP_FIELD = protobuf.FieldDescriptor()

CHATTYPE_E.PB_CHAT_WORLD.name = "PB_CHAT_WORLD"
CHATTYPE_E.PB_CHAT_WORLD.index = 0
CHATTYPE_E.PB_CHAT_WORLD.number = 1
CHATTYPE_E.PB_CHAT_UNION.name = "PB_CHAT_UNION"
CHATTYPE_E.PB_CHAT_UNION.index = 1
CHATTYPE_E.PB_CHAT_UNION.number = 2
CHATTYPE_E.PB_CHAT_PRIVATE.name = "PB_CHAT_PRIVATE"
CHATTYPE_E.PB_CHAT_PRIVATE.index = 2
CHATTYPE_E.PB_CHAT_PRIVATE.number = 3
CHATTYPE.name = "ChatType"
CHATTYPE.full_name = ".sgland.ChatType"
CHATTYPE.values = {CHATTYPE_E.PB_CHAT_WORLD,CHATTYPE_E.PB_CHAT_UNION,CHATTYPE_E.PB_CHAT_PRIVATE}
CHAT_F.TYPE_FIELD.name = "type"
CHAT_F.TYPE_FIELD.full_name = ".sgland.Chat.type"
CHAT_F.TYPE_FIELD.number = 1
CHAT_F.TYPE_FIELD.index = 0
CHAT_F.TYPE_FIELD.label = 2
CHAT_F.TYPE_FIELD.has_default_value = false
CHAT_F.TYPE_FIELD.default_value = nil
CHAT_F.TYPE_FIELD.enum_type = CHATTYPE
CHAT_F.TYPE_FIELD.type = 14
CHAT_F.TYPE_FIELD.cpp_type = 8

CHAT_F.USER_INFO_FIELD.name = "user_info"
CHAT_F.USER_INFO_FIELD.full_name = ".sgland.Chat.user_info"
CHAT_F.USER_INFO_FIELD.number = 2
CHAT_F.USER_INFO_FIELD.index = 1
CHAT_F.USER_INFO_FIELD.label = 1
CHAT_F.USER_INFO_FIELD.has_default_value = false
CHAT_F.USER_INFO_FIELD.default_value = nil
CHAT_F.USER_INFO_FIELD.message_type = Data_pb.USERINFO
CHAT_F.USER_INFO_FIELD.type = 11
CHAT_F.USER_INFO_FIELD.cpp_type = 10

CHAT_F.CONTENT_FIELD.name = "content"
CHAT_F.CONTENT_FIELD.full_name = ".sgland.Chat.content"
CHAT_F.CONTENT_FIELD.number = 3
CHAT_F.CONTENT_FIELD.index = 2
CHAT_F.CONTENT_FIELD.label = 2
CHAT_F.CONTENT_FIELD.has_default_value = false
CHAT_F.CONTENT_FIELD.default_value = ""
CHAT_F.CONTENT_FIELD.type = 9
CHAT_F.CONTENT_FIELD.cpp_type = 9

CHAT_F.TIMESTAMP_FIELD.name = "timestamp"
CHAT_F.TIMESTAMP_FIELD.full_name = ".sgland.Chat.timestamp"
CHAT_F.TIMESTAMP_FIELD.number = 4
CHAT_F.TIMESTAMP_FIELD.index = 3
CHAT_F.TIMESTAMP_FIELD.label = 2
CHAT_F.TIMESTAMP_FIELD.has_default_value = false
CHAT_F.TIMESTAMP_FIELD.default_value = 0
CHAT_F.TIMESTAMP_FIELD.type = 3
CHAT_F.TIMESTAMP_FIELD.cpp_type = 2

CHAT_F.IS_IMPORTANT_FIELD.name = "is_important"
CHAT_F.IS_IMPORTANT_FIELD.full_name = ".sgland.Chat.is_important"
CHAT_F.IS_IMPORTANT_FIELD.number = 5
CHAT_F.IS_IMPORTANT_FIELD.index = 4
CHAT_F.IS_IMPORTANT_FIELD.label = 1
CHAT_F.IS_IMPORTANT_FIELD.has_default_value = false
CHAT_F.IS_IMPORTANT_FIELD.default_value = false
CHAT_F.IS_IMPORTANT_FIELD.type = 8
CHAT_F.IS_IMPORTANT_FIELD.cpp_type = 7

CHAT.name = "Chat"
CHAT.full_name = ".sgland.Chat"
CHAT.nested_types = {}
CHAT.enum_types = {}
CHAT.fields = {CHAT_F.TYPE_FIELD, CHAT_F.USER_INFO_FIELD, CHAT_F.CONTENT_FIELD, CHAT_F.TIMESTAMP_FIELD, CHAT_F.IS_IMPORTANT_FIELD}
CHAT.is_extendable = false
CHAT.extensions = {}
CHATSENDREQ_F.TYPE_FIELD.name = "type"
CHATSENDREQ_F.TYPE_FIELD.full_name = ".sgland.ChatSendReq.type"
CHATSENDREQ_F.TYPE_FIELD.number = 1
CHATSENDREQ_F.TYPE_FIELD.index = 0
CHATSENDREQ_F.TYPE_FIELD.label = 2
CHATSENDREQ_F.TYPE_FIELD.has_default_value = false
CHATSENDREQ_F.TYPE_FIELD.default_value = nil
CHATSENDREQ_F.TYPE_FIELD.enum_type = CHATTYPE
CHATSENDREQ_F.TYPE_FIELD.type = 14
CHATSENDREQ_F.TYPE_FIELD.cpp_type = 8

CHATSENDREQ_F.ID_FIELD.name = "id"
CHATSENDREQ_F.ID_FIELD.full_name = ".sgland.ChatSendReq.id"
CHATSENDREQ_F.ID_FIELD.number = 2
CHATSENDREQ_F.ID_FIELD.index = 1
CHATSENDREQ_F.ID_FIELD.label = 1
CHATSENDREQ_F.ID_FIELD.has_default_value = false
CHATSENDREQ_F.ID_FIELD.default_value = 0
CHATSENDREQ_F.ID_FIELD.type = 3
CHATSENDREQ_F.ID_FIELD.cpp_type = 2

CHATSENDREQ_F.CONTENT_FIELD.name = "content"
CHATSENDREQ_F.CONTENT_FIELD.full_name = ".sgland.ChatSendReq.content"
CHATSENDREQ_F.CONTENT_FIELD.number = 3
CHATSENDREQ_F.CONTENT_FIELD.index = 2
CHATSENDREQ_F.CONTENT_FIELD.label = 2
CHATSENDREQ_F.CONTENT_FIELD.has_default_value = false
CHATSENDREQ_F.CONTENT_FIELD.default_value = ""
CHATSENDREQ_F.CONTENT_FIELD.type = 9
CHATSENDREQ_F.CONTENT_FIELD.cpp_type = 9

CHATSENDREQ.name = "ChatSendReq"
CHATSENDREQ.full_name = ".sgland.ChatSendReq"
CHATSENDREQ.nested_types = {}
CHATSENDREQ.enum_types = {}
CHATSENDREQ.fields = {CHATSENDREQ_F.TYPE_FIELD, CHATSENDREQ_F.ID_FIELD, CHATSENDREQ_F.CONTENT_FIELD}
CHATSENDREQ.is_extendable = false
CHATSENDREQ.extensions = {}
SGLCHATMSG_F.CHAT_SEND_REQ_FIELD.name = "chat_send_req"
SGLCHATMSG_F.CHAT_SEND_REQ_FIELD.full_name = ".sgland.SglChatMsg.chat_send_req"
SGLCHATMSG_F.CHAT_SEND_REQ_FIELD.number = 1100
SGLCHATMSG_F.CHAT_SEND_REQ_FIELD.index = 0
SGLCHATMSG_F.CHAT_SEND_REQ_FIELD.label = 1
SGLCHATMSG_F.CHAT_SEND_REQ_FIELD.has_default_value = false
SGLCHATMSG_F.CHAT_SEND_REQ_FIELD.default_value = nil
SGLCHATMSG_F.CHAT_SEND_REQ_FIELD.message_type = CHATSENDREQ
SGLCHATMSG_F.CHAT_SEND_REQ_FIELD.type = 11
SGLCHATMSG_F.CHAT_SEND_REQ_FIELD.cpp_type = 10

SGLCHATMSG_F.CHAT_RECEIVE_RESP_FIELD.name = "chat_receive_resp"
SGLCHATMSG_F.CHAT_RECEIVE_RESP_FIELD.full_name = ".sgland.SglChatMsg.chat_receive_resp"
SGLCHATMSG_F.CHAT_RECEIVE_RESP_FIELD.number = 1100
SGLCHATMSG_F.CHAT_RECEIVE_RESP_FIELD.index = 1
SGLCHATMSG_F.CHAT_RECEIVE_RESP_FIELD.label = 3
SGLCHATMSG_F.CHAT_RECEIVE_RESP_FIELD.has_default_value = false
SGLCHATMSG_F.CHAT_RECEIVE_RESP_FIELD.default_value = {}
SGLCHATMSG_F.CHAT_RECEIVE_RESP_FIELD.message_type = CHAT
SGLCHATMSG_F.CHAT_RECEIVE_RESP_FIELD.type = 11
SGLCHATMSG_F.CHAT_RECEIVE_RESP_FIELD.cpp_type = 10

SGLCHATMSG.name = "SglChatMsg"
SGLCHATMSG.full_name = ".sgland.SglChatMsg"
SGLCHATMSG.nested_types = {}
SGLCHATMSG.enum_types = {}
SGLCHATMSG.fields = {}
SGLCHATMSG.is_extendable = false
SGLCHATMSG.extensions = {SGLCHATMSG_F.CHAT_SEND_REQ_FIELD, SGLCHATMSG_F.CHAT_RECEIVE_RESP_FIELD}

Chat = protobuf.Message(CHAT)
ChatSendReq = protobuf.Message(CHATSENDREQ)
PB_CHAT_PRIVATE = 3
PB_CHAT_UNION = 2
PB_CHAT_WORLD = 1
SglChatMsg = protobuf.Message(SGLCHATMSG)

SglMsg_pb.SglReqMsg.RegisterExtension(SGLCHATMSG_F.CHAT_SEND_REQ_FIELD)
SglMsg_pb.SglRespMsg.RegisterExtension(SGLCHATMSG_F.CHAT_RECEIVE_RESP_FIELD)
